development:
  adapter: postgresql
  encoding: unicode
  database: redirector_development
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: redirector_test
  pool: 5
  host: localhost
  password:
